const express = require('express');
const auth = require('../../auth/Auth');
const SessionCtrl = require('./SessionCtrl');
const route = express.Router();

route
  .get('/', auth.verifyToken, SessionCtrl.getSessions)
  .get('/:sessionId', auth.verifyToken, SessionCtrl.getSessionDetail)
  .get('/:sessionId/users', auth.verifyToken, SessionCtrl.getSessionUsers)
  .get('/:sessionId/sessionData',auth.verifyToken, SessionCtrl.getSessionShppingandEquipmentList)
  // .put('/:sessionId/:userId', auth.verifyToken, SessionCtrl.updateSessionUser)
  .put('/:sessionId/joinstatus', auth.verifyToken, SessionCtrl.updateSessionStatus)
  .put('/:sessionId/updatestatus', auth.verifyToken, SessionCtrl.updateSessionjoinStatus)

  .put('/:sessionId/completed', auth.verifyToken, SessionCtrl.sessionCompleted)
  .put('/:sessionId/CancelSession',auth.verifyToken, SessionCtrl.sessionCancel)
  .put('/:sessionId/stream-id', auth.verifyToken, SessionCtrl.updateUserStream)
  .get('/:sessionId/:userId/stream-id', auth.verifyToken, SessionCtrl.getStreamUser)
  .post('/activity-log', auth.verifyToken, SessionCtrl.activityLogs)

  .get('/:channelId/channel',auth.verifyToken, SessionCtrl.getSessionsByChannel)
  .get('/:sessionId/sess',auth.verifyToken, SessionCtrl.getSessionDetail1)
  .get('/:userId/product', SessionCtrl.getAllProductByHost)
  .get('/:sessionId', auth.verifyToken, SessionCtrl.getSessions1)
  //.post('/create', auth.verifyToken, SessionCtrl.createSession)
  .post('/create', auth.verifyToken, SessionCtrl.createSession)
  .put('/:sessionId/editFitnessSession', auth.verifyToken, SessionCtrl.editFitnessSession)
  .get('/:sessionId/individualsessiondetail', auth.verifyToken, SessionCtrl.individualSessionDetail)
  .get('/:sessionId/individualsessiondetailForAdmin',  SessionCtrl.individualSessionDetailForAdmin)
  .get('/:sessionId/getEmojiesBysessionProduct', SessionCtrl.getemojiesbysessionProduct)
  .get('/check/:sessionName', auth.verifyToken, SessionCtrl.checkDuplicateSession)
  //.get('/hosts-list/:channelId', auth.verifyToken, SessionCtrl.getHosts)
  //.get('/hosts-list1/:channelId', SessionCtrl.getHosts)
  .get('/:channelId/hosts-list1', SessionCtrl.getHosts)
  .get('/:channelId/hosts-user-list',auth.verifyToken, SessionCtrl.getHostsForChannel)
  //.get('/equipments/:interestId', SessionCtrl.getEquipments)
  .get('/:interestId/equipments', SessionCtrl.getEquipments)
  //.get('/shoppinglist/:interestId', SessionCtrl.getShoppingList)
  .get('/:interestId/shoppinglist', SessionCtrl.getShoppingList)
  //.get('/activityType/:interestId', SessionCtrl.getActivityType)
  .get('/:interestId/activityType', SessionCtrl.getActivityType)
  .post('/createwineSession', auth.verifyToken, SessionCtrl.createWineSession)
  .put('/:sessionId/editWineSession', auth.verifyToken, SessionCtrl.editwineSession)
  .get('/:interestId/emojiesList', SessionCtrl.getEmojiesList)
  .get('/:channelId/product-list', SessionCtrl.getProductList)
  .get('/:interestId/attributeList', SessionCtrl.getAttributeList)
  .get('/:interestId/sessionList', SessionCtrl.getSessionListByInterestId)
  .post('/addProduct', auth.verifyToken, SessionCtrl.addNewProduct)
  //.get('/:channelId/interest', SessionCtrl.getInterestBychannelId)
  .get('/:channelId/allInterest', SessionCtrl.getInterest) 
  .get('/channelList/Host',auth.verifyToken, SessionCtrl.getchannelListByHost) 
  .get('/:channelId/individualChannelDetails',auth.verifyToken, SessionCtrl.getIndividualChanneldetails) 
  .post('/createchannel',auth.verifyToken, SessionCtrl.createNewChannel)
  .put('/:channelId/editChannel', auth.verifyToken, SessionCtrl.editNewChannel)
  .post('/verifyuser', SessionCtrl.verifyUser)
  .post('/saveSessionHistory',auth.verifyToken, SessionCtrl.sessionHistorySave)
  .post('/createDefaultSession', SessionCtrl.createDefault11Session)
  .post('/addInterestOnChannel',  SessionCtrl.add_interestOnChannel)
  .delete('/:channelId/deleteInterestOnChannel',  SessionCtrl.delete_interestOnChannel)
 
  //.post('/addMember',  SessionCtrl.addMemberChannelWise)
  .post('/member',  SessionCtrl.addMemberChannelWise)
  //.get('/:channelId/getMember',  SessionCtrl.getMemberChannelWise)
  .get('/member/:channelId',  SessionCtrl.getMemberChannelWise)
 // .put('/:memberId/editMember',  SessionCtrl.editMemberChannelWise)
  .put('/member',  SessionCtrl.editMemberChannelWise)
  //.put('/:memberId/updateMember',  SessionCtrl.updateMemberchannelWise)
  .patch('/member',  SessionCtrl.updateMemberchannelWise)
  //.delete('/:memberId/deleteMember',  SessionCtrl.deleteMemberChannelWise)
  .delete('/member',  SessionCtrl.deleteMemberChannelWise)
  

  .get('/:sessionId/sessionUserExist',auth.verifyToken, SessionCtrl.getSessionUserExist)
  .get('/host/defaultSessionCompleted', auth.verifyToken, SessionCtrl.getDefaultSessionCompleted)
  .put('/host/updateDefaultSession', SessionCtrl.updateDefaultSessionStatus)
  .put('/host/updateDefaultSessionIstutorialStart', SessionCtrl.updateDefaultSessionTutorialStart)
  .post('/host/updateDefaultSessionTime',auth.verifyToken, SessionCtrl.updateDefaultSessionEndTime)
  .get('/host/updateIsTutorialRead',auth.verifyToken, SessionCtrl.updateIsTutorialRead)
 
  module.exports = route;
